#1 updated-git-ignore-file with the code provided
Aleenatjames/WordPressProject pull request #2
Opened 2024-10-24 12:38 UTC by Aleenatjames

2024-10-24 12:51 UTC, AbhijithHaridas requested changes
@Aleenatjames, you forgot to remove the files mentioned in `.gitignore`

2024-10-24 12:59 UTC, Aleenatjames commented
Updated the git ignore file

2024-10-24 13:27 UTC, AbhijithHaridas requested changes
@Aleenatjames remove Akismet plugin

2024-10-25 04:48 UTC, AbhijithHaridas approved these changes

2024-10-25 04:49 UTC, merged